import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import { COLORS } from '../constants/colors';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: COLORS.primary,
    primaryContainer: COLORS.primaryLight,
    secondary: COLORS.secondary,
    secondaryContainer: COLORS.secondaryLight,
    tertiary: COLORS.info,
    error: COLORS.error,
    errorContainer: COLORS.errorLight,
    background: COLORS.gray[50],
    surface: COLORS.white,
    surfaceVariant: COLORS.gray[100],
    onPrimary: COLORS.white,
    onSecondary: COLORS.white,
    onBackground: COLORS.text.primary,
    onSurface: COLORS.text.primary,
    outline: COLORS.border.light,
    success: COLORS.success,
    warning: COLORS.warning,
    elevation: {
      level0: 'transparent',
      level1: COLORS.white,
      level2: COLORS.white,
      level3: COLORS.white,
      level4: COLORS.white,
      level5: COLORS.white,
    },
  },
  fonts: {
    ...MD3LightTheme.fonts,
    displayLarge: { ...MD3LightTheme.fonts.displayLarge, fontWeight: '700' },
    displayMedium: { ...MD3LightTheme.fonts.displayMedium, fontWeight: '700' },
    displaySmall: { ...MD3LightTheme.fonts.displaySmall, fontWeight: '700' },
    headlineLarge: { ...MD3LightTheme.fonts.headlineLarge, fontWeight: '600' },
    headlineMedium: { ...MD3LightTheme.fonts.headlineMedium, fontWeight: '600' },
    headlineSmall: { ...MD3LightTheme.fonts.headlineSmall, fontWeight: '600' },
    titleLarge: { ...MD3LightTheme.fonts.titleLarge, fontWeight: '600' },
    titleMedium: { ...MD3LightTheme.fonts.titleMedium, fontWeight: '500' },
    titleSmall: { ...MD3LightTheme.fonts.titleSmall, fontWeight: '500' },
  },
  roundness: 12,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: COLORS.primary,
    primaryContainer: COLORS.primaryDark,
    secondary: COLORS.secondaryLight,
    secondaryContainer: COLORS.secondary,
    tertiary: COLORS.infoLight,
    error: COLORS.errorLight,
    errorContainer: COLORS.errorDark,
    background: COLORS.gray[900],
    surface: COLORS.gray[800],
    surfaceVariant: COLORS.gray[700],
    onPrimary: COLORS.white,
    onSecondary: COLORS.white,
    onBackground: COLORS.white,
    onSurface: COLORS.white,
    outline: COLORS.gray[600],
    success: COLORS.successLight,
    warning: COLORS.warningLight,
    elevation: {
      level0: 'transparent',
      level1: COLORS.gray[850] || COLORS.gray[800],
      level2: COLORS.gray[800],
      level3: COLORS.gray[750] || COLORS.gray[700],
      level4: COLORS.gray[700],
      level5: COLORS.gray[650] || COLORS.gray[600],
    },
  },
  fonts: {
    ...MD3DarkTheme.fonts,
    displayLarge: { ...MD3DarkTheme.fonts.displayLarge, fontWeight: '700' },
    displayMedium: { ...MD3DarkTheme.fonts.displayMedium, fontWeight: '700' },
    displaySmall: { ...MD3DarkTheme.fonts.displaySmall, fontWeight: '700' },
    headlineLarge: { ...MD3DarkTheme.fonts.headlineLarge, fontWeight: '600' },
    headlineMedium: { ...MD3DarkTheme.fonts.headlineMedium, fontWeight: '600' },
    headlineSmall: { ...MD3DarkTheme.fonts.headlineSmall, fontWeight: '600' },
    titleLarge: { ...MD3DarkTheme.fonts.titleLarge, fontWeight: '600' },
    titleMedium: { ...MD3DarkTheme.fonts.titleMedium, fontWeight: '500' },
    titleSmall: { ...MD3DarkTheme.fonts.titleSmall, fontWeight: '500' },
  },
  roundness: 12,
};
