import React, { useRef } from 'react';
import { Printer, Download, Calendar, BarChart2, Users, ShoppingCart, Star } from 'lucide-react';

interface PrintableReportProps {
  darkMode?: boolean;
  reportType: 'bookings' | 'users' | 'reviews' | 'analytics';
  title: string;
  dateRange?: { start: string; end: string };
  data: any;
  summary?: Record<string, string | number>;
}

export function PrintableReport({
  darkMode = false,
  reportType,
  title,
  dateRange,
  data,
  summary,
}: PrintableReportProps) {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    const printContent = printRef.current;
    if (!printContent) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - Accuro Report</title>
          <style>
            * {
              margin: 0;
              padding: 0;
              box-sizing: border-box;
            }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              font-size: 12px;
              line-height: 1.5;
              color: #1f2937;
              padding: 20px;
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              padding-bottom: 20px;
              border-bottom: 2px solid #e5e7eb;
            }
            .header h1 {
              font-size: 24px;
              color: #1e40af;
              margin-bottom: 5px;
            }
            .header p {
              color: #6b7280;
              font-size: 14px;
            }
            .date-range {
              font-size: 12px;
              color: #6b7280;
              margin-top: 10px;
            }
            .summary {
              display: flex;
              justify-content: center;
              gap: 30px;
              margin-bottom: 30px;
              flex-wrap: wrap;
            }
            .summary-item {
              text-align: center;
              padding: 15px 25px;
              background: #f3f4f6;
              border-radius: 8px;
            }
            .summary-item .value {
              font-size: 24px;
              font-weight: bold;
              color: #1e40af;
            }
            .summary-item .label {
              font-size: 12px;
              color: #6b7280;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th, td {
              padding: 10px 12px;
              text-align: left;
              border-bottom: 1px solid #e5e7eb;
            }
            th {
              background: #f9fafb;
              font-weight: 600;
              color: #374151;
              font-size: 11px;
              text-transform: uppercase;
            }
            tr:hover {
              background: #f9fafb;
            }
            .status-badge {
              display: inline-block;
              padding: 2px 8px;
              border-radius: 12px;
              font-size: 10px;
              font-weight: 500;
            }
            .status-pending { background: #fef3c7; color: #92400e; }
            .status-confirmed { background: #d1fae5; color: #065f46; }
            .status-completed { background: #dbeafe; color: #1e40af; }
            .status-cancelled { background: #fee2e2; color: #991b1b; }
            .footer {
              margin-top: 30px;
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              text-align: center;
              font-size: 10px;
              color: #9ca3af;
            }
            @media print {
              body { padding: 0; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          ${printContent.innerHTML}
          <div class="footer">
            <p>Generated by Accuro on ${new Date().toLocaleString()}</p>
            <p>This is a computer-generated report.</p>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  const renderTable = () => {
    if (!data || data.length === 0) {
      return <p className="text-gray-500 text-center py-4">No data available</p>;
    }

    switch (reportType) {
      case 'bookings':
        return (
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Customer</th>
                <th>Product</th>
                <th>Status</th>
                <th>Contact</th>
              </tr>
            </thead>
            <tbody>
              {data.map((item: any) => (
                <tr key={item._id}>
                  <td>{new Date(item.preferredDate).toLocaleDateString()}</td>
                  <td>
                    <div>{item.name}</div>
                    <div style={{ fontSize: '10px', color: '#6b7280' }}>{item.company || '-'}</div>
                  </td>
                  <td>{item.product}</td>
                  <td>
                    <span className={`status-badge status-${item.status}`}>{item.status}</span>
                  </td>
                  <td>
                    <div>{item.email}</div>
                    <div style={{ fontSize: '10px', color: '#6b7280' }}>{item.phone}</div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      case 'users':
        return (
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Verified</th>
                <th>Logins</th>
                <th>Joined</th>
              </tr>
            </thead>
            <tbody>
              {data.map((item: any) => (
                <tr key={item._id}>
                  <td>{item.name}</td>
                  <td>{item.email}</td>
                  <td>{item.role}</td>
                  <td>{item.isEmailVerified ? 'Yes' : 'No'}</td>
                  <td>{item.loginCount || 0}</td>
                  <td>{new Date(item.createdAt).toLocaleDateString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      case 'reviews':
        return (
          <table>
            <thead>
              <tr>
                <th>Reviewer</th>
                <th>Rating</th>
                <th>Comment</th>
                <th>Status</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {data.map((item: any) => (
                <tr key={item._id}>
                  <td>{item.name}</td>
                  <td>{'★'.repeat(item.rating)}{'☆'.repeat(5 - item.rating)}</td>
                  <td style={{ maxWidth: '300px' }}>{item.comment?.substring(0, 100)}...</td>
                  <td>{item.isApproved ? 'Approved' : 'Pending'}</td>
                  <td>{new Date(item.createdAt).toLocaleDateString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      default:
        return null;
    }
  };

  const getIcon = () => {
    switch (reportType) {
      case 'bookings':
        return <Calendar className="text-blue-500" size={20} />;
      case 'users':
        return <Users className="text-blue-500" size={20} />;
      case 'reviews':
        return <Star className="text-blue-500" size={20} />;
      case 'analytics':
        return <BarChart2 className="text-blue-500" size={20} />;
      default:
        return <ShoppingCart className="text-blue-500" size={20} />;
    }
  };

  return (
    <div>
      {/* Print Button */}
      <div className="flex justify-end gap-2 mb-4 no-print">
        <button
          onClick={handlePrint}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg transition ${
            darkMode
              ? 'bg-blue-600 text-white hover:bg-blue-700'
              : 'bg-blue-600 text-white hover:bg-blue-700'
          }`}
        >
          <Printer size={18} />
          Print Report
        </button>
      </div>

      {/* Printable Content */}
      <div
        ref={printRef}
        className={`p-6 rounded-lg border ${
          darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'
        }`}
      >
        {/* Header */}
        <div className="header">
          <div className="flex items-center justify-center gap-2 mb-2">
            {getIcon()}
            <h1 style={{ fontSize: '24px', color: '#1e40af' }}>{title}</h1>
          </div>
          <p style={{ color: '#6b7280' }}>Accuro Business Report</p>
          {dateRange && (
            <p className="date-range">
              Period: {new Date(dateRange.start).toLocaleDateString()} - {new Date(dateRange.end).toLocaleDateString()}
            </p>
          )}
        </div>

        {/* Summary */}
        {summary && Object.keys(summary).length > 0 && (
          <div className="summary">
            {Object.entries(summary).map(([label, value]) => (
              <div key={label} className="summary-item">
                <div className="value">{value}</div>
                <div className="label">{label}</div>
              </div>
            ))}
          </div>
        )}

        {/* Data Table */}
        {renderTable()}
      </div>
    </div>
  );
}

// Print styles component to inject global print styles
export function PrintStyles() {
  return (
    <style>{`
      @media print {
        body * {
          visibility: hidden;
        }
        .print-area, .print-area * {
          visibility: visible;
        }
        .print-area {
          position: absolute;
          left: 0;
          top: 0;
          width: 100%;
        }
        .no-print {
          display: none !important;
        }
        @page {
          margin: 1cm;
        }
      }
    `}</style>
  );
}
